# Generated by Django 3.2.8 on 2022-01-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_sap', '0002_auto_20220116_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
